### ISSUE TITLE
resources folder

### ISSUE THREAD

**Issue by fafayqa** [macroing/Dayflower#1]
I am trying to add this into NetBeansIDE 12.4, all seems fine except the resources folder where all of the files have errors in all of its lines, what is wrong with that folder? How in the world can a Java class has structure like this example below (BullseyeMaterial.java in resources folder)???

```
final Light light1 = new PerezLight();

final Material material1 = new MatteMaterial(new CheckerboardTexture());
final Material material2 = new BullseyeMaterial(new MatteMaterial(new Color3F(1.0F, 0.01F, 0.01F)), new MatteMaterial(new Color3F(0.01F, 1.0F, 0.01F)), new Point3F(10.0F, 10.0F, 10.0F));

final Shape3F shape1 = new Plane3F();
final Shape3F shape2 = new Sphere3F();

final Transform transform1 = new Transform(new Point3F(0.0F, 0.0F, 0.0F));
final Transform transform2 = new Transform(new Point3F(0.0F, 1.0F, 0.0F), Quaternion4F.from(Matrix44F.rotateX(AngleF.degrees(270.0F))));

final Primitive primitive1 = new Primitive(material1, shape1, transform1);
final Primitive primitive2 = new Primitive(material2, shape2, transform2);

final Camera camera = new Camera(new Point3F(0.0F, 2.0F, -10.0F), AngleF.degrees(40.0F));

scene.addLight(light1);
scene.addPrimitive(primitive1);
scene.addPrimitive(primitive2);
scene.setCamera(camera);
scene.setName("BullseyeMaterial");
```
Because of that I cannot run/test anything at all...

**Comment by macroing** [comment]
I use Eclipse myself, so I have not tried to import it into NetBeans. For me the resources folder is just a folder and not a source folder.

The .java files in the resources/scenes folder contain snippets of Java source code that are used in conjunction with a org.dayflower.scene.SceneLoader called org.dayflower.scene.loader.JavaSceneLoader. It loads the content of a file, compiles it and executes it. This simplifies the process of creating new scenes to render.

**Comment by fafayqa** [comment]
Sure, folder is a folder, but NetBeansIDE checks all *.java files in those folders for errors, and that what you have there is simply not correct java file syntax.

Thus you SHOULD change its (file's) extension to something else (it can literally be whatever you want), definitely not having it as *.java, cos then it is very misleading + it produces those code errors in IDEs that actually do care for the code syntax (I do not know how it is in Eclipse). Think about it.
