### ISSUE TITLE
[Question] License?

### ISSUE THREAD

**Issue by madhephaestus** [macroing/Dayflower#11]
You have LGPL and GPL in the repo, that seems like a contradiction? 

I would need LGPL to really incorporate this as a feature, can you clarify how the licensing works from your perspective? Since its all your code, if you just choose to remove the GPL license then this can (and IMHO should) be a major step forward in Java rendering standards!

**Comment by macroing** [comment]
When I read about LGPL (which is the license I wanted to use), I remember that I needed to have both COPYING and COPYING.LESSER as files in the project. Is that perhaps incorrect? In the past, GitHub would only display LGPL as license. That must have changed.

The following can be found in COPYING.LESSER:

```
  This version of the GNU Lesser General Public License incorporates
the terms and conditions of version 3 of the GNU General Public
License, supplemented by the additional permissions listed below.
...
```

**Comment by madhephaestus** [comment]
Yeah, keeping the old GPL around means the GPL restrictions apply. Since
I'm not the author, you are, I can't remove it and I have to keep it
around. You are free to remove it since you are the author.

**Comment by macroing** [comment]
Here I found some instructions for use of LGPL:
https://www.gnu.org/licenses/gpl-howto.html

An excerpt:
> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs we conventionally put the license in a file called COPYING.
> 
> If you are releasing your program under the GNU AGPL, use the text version of the GNU AGPL instead of the GNU GPL.
> 
> If you are releasing your program under the Lesser GPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's crucial to include both licenses so users have all the materials they need to understand their rights.

**Comment by madhephaestus** [comment]
Ok, cool. My understanding of the LGPL was that it was self contained, or referenced. Back when i owned a robotics business my lawyer had told me the opposite of that. Ah well, in any case this issue serves as explicate clarification of LGPL intent. 
Thank you for being patient with me!
