### ISSUE TITLE
Recent dependancy change broke Java 8 support

### ISSUE THREAD

**Issue by madhephaestus** [macroing/Dayflower#12]
A change in the dependencies causes Java 8 builds of the source to fail to compile. 

```
Could not instrument class org/macroing/java/io/Files: Unsupported class file major version 61.
```

**Comment by macroing** [comment]
I made a new commit with a fix, I hope. Not tested it on my old computer yet, where I run Java 8. I run Java 17 on my new computer.

**Comment by madhephaestus** [comment]
That works great, thanks!
