### ISSUE TITLE
Main Dayflower application stays loaded in NetBeansIDE

### ISSUE THREAD

**Issue by fafayqa** [macroing/Dayflower#3]
When I run the app in NetBeansIDE, do nothing and just lose it, all is fine.
But if I start some render and then close the application, it still remains loaded and runing, only the GUI is closed.

**Comment by macroing** [comment]
I just fixed that bug. All renderers are stopped on close. Similar to File > Exit.

**Comment by fafayqa** [comment]
OK< that is good! When it will be available for download? Or is it available immediately?

**Comment by macroing** [comment]
The code is available in the last commit to the master branch (which is the only branch at this point).
